version: '3'
services:

#  postgres:
#    image: postgres:11.3
#    restart: always
#    environment:
#      POSTGRES_USER: admin
#      POSTGRES_PASSWORD: admin
#    ports:
#      - 5432:5432
#    volumes:
#      - postgres:/var/lib/postgresql/data

  mysql:
    image: mysql:5.7.26
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    restart: always

volumes:
  postgres: ~
  mysql: ~
